version: 2

models:
  - name: int_customers_cleaned
    description: "Modelo intermedio que limpia y estandariza los datos."
    columns:
      - name: C_CUSTKEY
        description: Clave primaria del customer
        data_tests:
          - unique
          - not_null